TakeProj/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.views.static import serve

from TakeProj import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('take_app.urls')),
    path('user_login/', include('django.contrib.auth.urls')),
    path('auth/', include('user_login.urls', namespace='user_login')),
    path('exchange/', include('gitcard_exchange.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reg_auth/', include('accounts.urls')),
    path('reg_auth/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('group/', include('base.urls')),
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'


urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='registration'),
    path('logout/', views.logout_user, name='logout')
    ]

base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.LoginPage, name="login"),
    path("register/", views.registerPage, name="register"),
    path("logout!/", views.logoutUser, name="logout"),
    path("room/<str:pk>/", views.room, name="room"),
    path("create-room/", views.createRoom, name="create-room"),
    path("update-room/<str:pk>/", views.UpdateRoom, name="update-room"),
    path("profile/<str:pk>/", views.userProfile, name="user-profile"),
    path("update-user/", views.updateUser, name="update-user"),
    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
    path("delete-room/<str:pk>/", views.deleteRoom, name="delete-room"),
    path("delete-message/<str:pk>/", views.deleteMessage, name="delete-message"),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Topic(models.Model):
    name = models.CharField(max_length=200)


    def __str__(self) -> str:
        return self.name




class Room(models.Model):
    host = models.ForeignKey(User, on_delete= models.SET_NULL ,  null=True)
    topic = models.ForeignKey(Topic , on_delete=models.SET_NULL , null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User,  related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name
    class Meta:
        ordering = [ '-updated' ,'-created']


class Message(models.Model):
    user =  models.ForeignKey(User, on_delete= models.CASCADE)
    room =  models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)



    class Meta:
        ordering = [ '-updated' ,'-created']


        
    def __str__(self) -> str:
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from .models import Room
from django.contrib.auth.models import User

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host',  'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer
from base.api import serializers


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/views.py
from django.shortcuts import render,redirect,  get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.decorators import   login_required
from django.contrib import messages
from django.contrib.auth.forms  import UserCreationForm
from .models import Room , Topic, Message
from .forms import RoomForm, UserForm
from django.db.models import Q

# Create your views here.
def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    rooms = Room.objects.filter(
        Q(topic__name__icontains= q) |
        Q(name__icontains= q)|
        Q(description__icontains= q)
                                
                                
                                )
    room_count = rooms.count()
    topics = Topic.objects.all()[0:5]
    context = {"rooms": rooms , 'topics': topics,
                'room_count': room_count,
                'room_messages': room_messages

                }
    return render(request, "base/home.html", context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all() 
    participants = room.participants.all()
    if request.method == 'POST':
        message  = Message.objects.create(
            body = request.POST.get('body'),
            user = request.user,
            room=room
        )
        room.participants.add(request.user)
        return redirect('room', pk=room.id)
    context = {"room": room, 'room_messages': room_messages, 'participants': participants}
    return render(request, "base/room.html", context)
 
def LoginPage(request):
    page = 'login'
    context = {'page': page}
    if request.user.is_authenticated:
        messages.error(request, "Apologies You're Already Logged in!  ")
        return redirect('home')
    if request.method == "POST":

        username = request.POST.get("username").lower()
        password =request.POST.get("password")
        try:
            user = User.objects.get(username=username)
            
        except:
            messages.error(request, "system Error!   ")
        user = authenticate(request, username=username,password=password)
        if user is not None:

            login(request,user)
            return redirect('home')
        else:
            messages.error(request, "Username or Password doesn't exist! check and try again")

    return render(request, 'base/login_register.html' , context)





def logoutUser(request):
    logout(request)
    return redirect('home')


def registerPage(request):
    page = 'register'
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user = user.username.lower()
            user.save()
            login(request,user)
            return redirect('home')
        else:
            messages.error(request, 'sorry!, something went wrong! we are trying to fix it!')
    context = {'page': page , 'form': form}
    return render(request, 'base/login_register.html', context)




@login_required(login_url='login')
def createRoom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    create = "create"
    context = {'form': form, 'create': create, 'topics': topics}
    
    if request.method == 'POST':
       topic_name = request.POST.get('topic')
       topic , created = Topic.objects.get_or_create(name=topic_name)
       Room.objects.create(
           host=request.user,
           topic=topic,
           name=request.POST.get('name'),
           description =request.POST.get('description')

       )
       return redirect('home')
       """  form = RoomForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.host = request.user
            room.save()
            return redirect('home') """

    return render (request,'base/room_form.html', context)


def userProfile(request,pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user':user , 
               'rooms': rooms,
               'room_messages': room_messages,
               'topics': topics,
               }
    
    return render(request, 'base/profile.html', context)

@login_required(login_url='login')
def UpdateRoom(request, pk):
    room = Room.objects.get(id=pk)
    topics = Topic.objects.all()
    form = RoomForm(instance=room)

    if request.user != room.host:
        messages.error(request, "Sorry! you're not  the foundation! and can't   update! this room")
        return redirect(  'home')
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic , created = Topic.objects.get_or_create(name=topic_name)
        form = RoomForm(request.POST, instance=room)# instance is just like id the room passed in is for id detecting the room tp update
        room.name = request.POST.get('name')
        room.topic =  topic
        room.description = request.POST.get('description')
        room.save()
         
        return redirect('home')
    context = {'form': form, 'topics':topics, 'room':room}
    return render(request, 'base/room_form.html',context  )


@login_required(login_url='login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)
    if request.user != room.host:
        messages.error(request, "Sorry! you're not  the foundation! and can't   delete! this room")
        return redirect(  'home')
    if request.method == 'POST':
        room.delete()
        return redirect('home')
    return render(request, 'base/delete.html',{'obj': room})


@login_required(login_url='login')
def deleteMessage(request, pk):
     
    message = Message.objects.get(id=pk)
    if request.user != message.user:
        messages.error(request, "Apologies! you cannot delete this message.")
        return redirect(  'room' , pk=room.id)
    if request.method == 'POST':
        message.delete()
        messages.error(request, " you've deleted the message.")
      
        return redirect('room', pk=message.room.id)
    return render(request, 'base/delete.html',{'obj': message})

@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)
    if request.method == 'POST':
        form = UserForm(request.POST,instance=user)
        if form.is_valid:
            form.save()
            return redirect('user-profile', pk=user.id)
    return render(request, 'base/update-user.html',{'form':form})



def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'base/topics.html', {'topics': topics})


def activityPage(request):
    room_messages = Message.objects.all()
    return render(request, 'base/activity.html', {'room_messages': room_messages})

TakeProj/templates/Takeproj/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, viewport-fit=cover">
	<meta name="apple-mobile-web-app-capable" content="yes">


	<!-- Page Title -->
	<title>New Template — Slides 4.1 Template Generator</title>

	<!-- Compressed Styles -->
	<link href="{% static 'css/style.css' %}" rel="stylesheet">


	<!-- Custom Styles -->
	<!-- <link href="css/custom.css" rel="stylesheet" type="text/css"> -->

	<!-- jQuery 3.3.1 -->
	<script src="{% static 'jss/second.js' %}" type="text/javascript"></script>
	<script src="{% static 'jss/index.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
		crossorigin="anonymous"></script>

	<!-- Custom Scripts -->
	<!-- <script src="js/custom.js" type="text/javascript"></script> -->

	<!-- Fonts and Material Icons -->
	<link rel="stylesheet" as="font"
		href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,600,700|Material+Icons">

</head>

<body class="slides chain simplifiedMobile animated">
	{% include 'Takeproj/svg.html' %}


	{% include 'Takeproj/navbars.html' %}


	<!-- Slide 1 (#09) -->
	{% block content %}
	{% endblock content %}

	{% include 'Takeproj/downnav.html' %}

</body>

</html>

TakeProj/templates/Takeproj/boostrap.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Hello, world</title>
</head>

<body style="background-image:url({% static 'image/img-09.jpg' %});">



  {% block content %}
  {% endblock content %}
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
  <script>
    $(document).ready(function () {
      $('#myModal').modal('show');
    });
  </script>

</body>

</html>

TakeProj/templates/Takeproj/downnav.html
<!-- Panel Bottom #15 -->
<nav class="panel bottom lastSlideOnly">
  <div class="sections">
    <div class="center"><a href="#" class="opacity-8">Available <svg style="height:21px;"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#apple"></use></svg> iPhone</a></div>
  </div>
</nav>

<!-- Loading Progress Bar -->
<div class="progress-bar blue"></div>

TakeProj/templates/Takeproj/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />

    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style/style.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style/main.css' %}">
    {% if title %}
    <title class="text-c">{{title}}</title>
    {% else %}
    <title class="text-c"> studybud unknown page</title>
    {% endif %}
</head>

<body>

    {% include 'navbar.html'%}

    <div class="  z-100 ">
        {% for message in messages %}
        <div class="text-danger text-center fw-bold py-2 text-center2 x">{{ message }} </div>
        {% endfor %}
    </div>


    {% block content %}

    {% endblock%}
    <script src="{%  static 'js/script.js'%}"></script>

</body>

</html>

TakeProj/templates/Takeproj/navbar.html
<!-- Navigation -->
<nav class="side pole">
  <div class="navigation">
    <ul></ul>
  </div>
</nav>

<!-- Panel Top #08 -->
<nav class="panel top">
  <div class="sections desktop">
    <div class="left"><a href="https://designmodo.com/?u=3165" title="Slides Framework"><svg style="width:82px;height:24px"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo"></use></svg></a></div>
    <div class="center">
      <ul class="menu uppercase">
        <li><a href="#">Tour</a></li>
        <li><a href="#">Upgrade</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">Explore</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'accounts:registration' %}">Sign Up</a></li>
      </ul>
    </div>
    <div class="right">
      <ul class="menu trim">
        <li><a href="http://facebook.com/designmodo" target="_blank"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#facebook"></use></svg></a></li>
        <li><a href="http://twitter.com/designmodo" target="_blank"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></a></li>
        <li class="cropRight"><a href="http://instagram.com/designmodo" class="trimRight" target="_blank"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#instagram"></use></svg></a></li>
      </ul>
    </div>
  </div>
  <div class="sections compact hidden">
    <div class="left"><a href="https://designmodo.com/?u=3165" title="Slides Framework"><svg style="width:82px;height:24px"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo"></use></svg></a></div>
    <div class="right"><span class="button actionButton sidebarTrigger" data-sidebar-id="1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu"></use></svg></span></div>
  </div>
</nav>

<!-- Sidebar -->
<nav class="sidebar" data-sidebar-id="1">
  <div class="close"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close"></use></svg></div>
  <div class="content">
    <a href="#" class="logo"><svg width="37" height="30"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo-icon"></use></svg></a>
    <ul class="mainMenu margin-top-3">
      <li><a href="#">All Goods</a></li>
      <li><a href="#">UI Kits</a></li>
      <li><a href="#">Icons</a></li>
      <li><a href="#">Mockups</a></li>
      <li><a href="#">Toolkit</a></li>
    </ul>
    <ul class="subMenu small opacity-8">
      <li><a href="#">Submit Product</a></li>
      <li><a href="#">FAQ</a></li>
      <li><a href="#">License</a></li>
      <li><a href="#">Terms &amp; Conditions</a></li>
      <li><a href="#">Privacy Policy</a></li>
      <li><a href="#">Contact Us</a></li>
    </ul>
    <ul class="social opacity-8">
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#facebook"></use></svg></a></li>
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></a></li>
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#instagram"></use></svg></a></li>
    </ul>
  </div>
</nav>

TakeProj/templates/Takeproj/navbars.html
<!-- Navigation -->
<nav class="side pole">
  <div class="navigation">
    <ul></ul>
  </div>
</nav>

<!-- Panel Top #08 -->
<nav class="panel top">
  <div class="sections desktop">
    <div class="left"><a href="https://designmodo.com/?u=3165" title="Slides Framework"><svg style="width:82px;height:24px"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo"></use></svg></a></div>
    <div class="center">
      <ul class="menu uppercase">
        <li><a href="#">Tour</a></li>
        <li><a href="#">Upgrade</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">Explore</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'accounts:registration' %}">Sign Up</a></li>
      </ul>
    </div>
    <div class="right">
      <ul class="menu trim">
        <li><a href="http://facebook.com/designmodo" target="_blank"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#facebook"></use></svg></a></li>
        <li><a href="http://twitter.com/designmodo" target="_blank"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></a></li>
        <li class="cropRight"><a href="http://instagram.com/designmodo" class="trimRight" target="_blank"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#instagram"></use></svg></a></li>
      </ul>
    </div>
  </div>
  <div class="sections compact hidden">
    <div class="left"><a href="https://designmodo.com/?u=3165" title="Slides Framework"><svg style="width:82px;height:24px"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo"></use></svg></a></div>
    <div class="right"><span class="button actionButton sidebarTrigger" data-sidebar-id="1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu"></use></svg></span></div>
  </div>
</nav>

<!-- Sidebar -->
<nav class="sidebar" data-sidebar-id="1">
  <div class="close"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close"></use></svg></div>
  <div class="content">
    <a href="#" class="logo"><svg width="37" height="30"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo-icon"></use></svg></a>
    <ul class="mainMenu margin-top-3">
      <li><a href="#">All Goods</a></li>
      <li><a href="#">UI Kits</a></li>
      <li><a href="#">Icons</a></li>
      <li><a href="#">Mockups</a></li>
      <li><a href="#">Toolkit</a></li>
    </ul>
    <ul class="subMenu small opacity-8">
      <li><a href="#">Submit Product</a></li>
      <li><a href="#">FAQ</a></li>
      <li><a href="#">License</a></li>
      <li><a href="#">Terms &amp; Conditions</a></li>
      <li><a href="#">Privacy Policy</a></li>
      <li><a href="#">Contact Us</a></li>
    </ul>
    <ul class="social opacity-8">
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#facebook"></use></svg></a></li>
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></a></li>
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#instagram"></use></svg></a></li>
    </ul>
  </div>
</nav>